from il2cpp.prelude import *  # noqa: F401,F403
from il2cpp.common import u64
from il2cpp.csharp import FA_STATIC, field_attrs

HEADER_PRELUDE = r'''#pragma once
// Generated by il2csharp --emit-h. IL2CPP runtime structs follow the
// Unity 6000.0 / metadata v31 x64 layout.
#include <stdint.h>
#include <stddef.h>

typedef void(*Il2CppMethodPointer)();

struct MethodInfo;

struct VirtualInvokeData
{
    Il2CppMethodPointer methodPtr;
    const MethodInfo* method;
};

struct Il2CppType
{
    void* data;
    unsigned int bits;
};

struct Il2CppClass;

union Il2CppRGCTXData
{
    void* rgctxDataDummy;
    const MethodInfo* method;
    const Il2CppType* type;
    Il2CppClass* klass;
};

struct Il2CppRuntimeInterfaceOffsetPair
{
    Il2CppClass* interfaceType;
    int32_t offset;
};

struct Il2CppClass_1
{
    void* image;
    void* gc_desc;
    const char* name;
    const char* namespaze;
    Il2CppType byval_arg;
    Il2CppType this_arg;
    Il2CppClass* element_class;
    Il2CppClass* castClass;
    Il2CppClass* declaringType;
    Il2CppClass* parent;
    void* generic_class;
    void* typeMetadataHandle;
    void* interopData;
    Il2CppClass* klass;
    void* fields;
    void* events;
    void* properties;
    void* methods;
    Il2CppClass** nestedTypes;
    Il2CppClass** implementedInterfaces;
    Il2CppRuntimeInterfaceOffsetPair* interfaceOffsets;
};

struct Il2CppClass_2
{
    Il2CppClass** typeHierarchy;
    void* unity_user_data;
    uint32_t initializationExceptionGCHandle;
    uint32_t cctor_started;
    uint32_t cctor_finished;
    size_t cctor_thread;
    void* genericContainerHandle;
    uint32_t instance_size;
    uint32_t actualSize;
    uint32_t element_size;
    int32_t native_size;
    uint32_t static_fields_size;
    uint32_t thread_static_fields_size;
    int32_t thread_static_fields_offset;
    uint32_t flags;
    uint32_t token;
    uint16_t method_count;
    uint16_t property_count;
    uint16_t field_count;
    uint16_t event_count;
    uint16_t nested_type_count;
    uint16_t vtable_count;
    uint16_t interfaces_count;
    uint16_t interface_offsets_count;
    uint8_t typeHierarchyDepth;
    uint8_t genericRecursionDepth;
    uint8_t rank;
    uint8_t minimumAlignment;
    uint8_t naturalAligment;
    uint8_t packingSize;
    uint8_t bitflags1;
    uint8_t bitflags2;
};

struct Il2CppObject
{
    Il2CppClass *klass;
    void *monitor;
};

struct Il2CppArray
{
    Il2CppClass *klass;
    void *monitor;
    void *bounds;
    size_t max_length;
};
'''


class HeaderEmitter:
    """Emit an il2cpp.h-style C header: _Fields/_VTable/_c/_o struct quartets
    per managed type, matching Il2CppDumper's header dump format."""

    C_PRIM = {0x02: 'bool', 0x03: 'uint16_t', 0x04: 'int8_t', 0x05: 'uint8_t',
              0x06: 'int16_t', 0x07: 'uint16_t', 0x08: 'int32_t', 0x09: 'uint32_t',
              0x0a: 'int64_t', 0x0b: 'uint64_t', 0x0c: 'float', 0x0d: 'double',
              0x16: 'void*', 0x18: 'void*', 0x19: 'void*'}

    def __init__(self, il2, out_path):
        self.il = il2
        self.meta = il2.meta
        self.path = out_path

    @staticmethod
    def cident(s):
        return re.sub(r'[^A-Za-z0-9]', '_', s).strip('_') or '_'

    def type_cname(self, ti):
        """Flattened C identifier: Namespace_Outer_Type (arity dropped)."""
        td = self.meta.typedefs[ti]
        parts = []
        d = ti
        hops = 0
        while 0 <= d < len(self.meta.typedefs) and hops < 10:
            t = self.meta.typedefs[d]
            parts.append(self.cident(re.sub(r'`\d+$', '', t.name)))
            d = t.declaring
            hops += 1
            if d < 0:
                break
        parts.reverse()
        if td.namespace:
            parts = [self.cident(x) for x in td.namespace.split('.')] + parts
        return '_'.join(parts)

    def enum_underlying(self, td):
        et = self.il.types[td.element] if 0 <= td.element < len(self.il.types) else None
        te = self.il._type_enum(et) if et else 0x08
        return self.C_PRIM.get(te, 'int32_t')

    def _genericinst_td(self, t):
        """typedef index of a genericinst's base type, or None."""
        o = self.il.bin.va2off(t[0])
        if o is None:
            return None
        tt = self.il.type_from_ptr(u64(self.il.bin.d, o))
        if tt and self.il._type_enum(tt) in (0x11, 0x12) and 0 <= tt[0] < len(self.meta.typedefs):
            return tt[0]
        return None

    def ctype(self, t, depth=0, subst=None):
        """C type for an Il2CppType tuple (data, bits); subst maps generic
        parameter (var) metadata index -> argument type tuple."""
        if t is None or depth > 6:
            return 'void*'
        data, _bits = t
        te = self.il._type_enum(t)
        if te == 0x01:
            return 'void'
        if te in self.C_PRIM:
            return self.C_PRIM[te]
        if te == 0x0e:  # string
            return 'struct System_String_o*'
        if te in (0x11, 0x12):  # valuetype / class
            if te == 0x12 and data == 0:
                return 'Il2CppObject*'
            td = self.meta.typedefs[data] if 0 <= data < len(self.meta.typedefs) else None
            if td is None:
                return 'void*'
            if td.is_enum:
                return self.enum_underlying(td)
            n = self.type_cname(data)
            return 'struct %s_o*' % n if te == 0x12 else 'struct %s_o' % n
        if te in (0x0f, 0x10):  # ptr / byref
            inner = self.il.type_from_ptr(data)
            return (self.ctype(inner, depth + 1, subst) + '*') if inner else 'void*'
        if te in (0x1d, 0x14):  # szarray / multidim
            return 'struct Il2CppArray*'
        if te == 0x15:  # genericinst
            base = self._genericinst_td(t)
            if base is not None:
                btd = self.meta.typedefs[base]
                if btd.is_enum:
                    return self.enum_underlying(btd)
                cn = self.cident(self.il.type_name(t, depth))
                return 'struct %s_o' % cn if btd.is_valuetype else 'struct %s_o*' % cn
            return 'void*'
        if te in (0x13, 0x1e) and subst is not None and data in subst:
            return self.ctype(subst[data], depth + 1)
        return 'void*'

    def _instance_fields(self, td, subst=None):
        out = []
        fo = self.il.field_offsets[td.index] if td.index < len(self.il.field_offsets) else None
        for k, fi in enumerate(self.meta.type_fields(td)):
            f = self.meta.fields[fi]
            ft = self.il.types[f.type] if 0 <= f.type < len(self.il.types) else None
            if ft is None:
                continue
            if field_attrs(self.il, f) & FA_STATIC:
                continue  # static: not part of instance layout
            out.append('\t%s %s;' % (self.ctype(ft, 0, subst), self.cident(f.name)))
        return out

    def _inst_args(self, t):
        """Argument type tuples of a genericinst type tuple."""
        o = self.il.bin.va2off(t[0])
        if o is None:
            return None
        io = self.il.bin.va2off(u64(self.il.bin.d, o + 8))
        if io is None:
            return None
        argc = u64(self.il.bin.d, io)
        argv = u64(self.il.bin.d, io + 8)
        args = []
        for k in range(min(argc, 16)):
            tp = self.il.bin.qword(argv + k * 8) if argv else None
            args.append(self.il.type_from_ptr(tp) if tp else None)
        return args

    def _vtable(self, td, n, out):
        """Emit <n>_VTable struct; return True if a named vtable was emitted."""
        if td.vtable_count <= 0:
            return False
        entries = []
        for s in range(td.vtable_count):
            mi = self.il.vtable_method(td.index, s)
            if mi is None:
                return False
            nm = self.cident(self.meta.methods[mi].name)
            if not nm or nm == '_':
                return False
            entries.append('_%d_%s' % (s, nm))
        out.append('struct %s_VTable {' % n)
        for e in entries:
            out.append('\tVirtualInvokeData %s;' % e)
        out.append('};')
        return True

    def _emit_quartet(self, td, n, out, subst=None, base_suffix=None):
        """Emit the _Fields/_VTable/_c/_o struct quartet for a type shape."""
        if td.is_enum:
            out.append('struct %s_Fields {' % n)
            out.append('\t%s value__;' % self.enum_underlying(td))
            out.append('};')
        else:
            base = ''
            if base_suffix:
                base = ' : %s_Fields' % base_suffix
            elif td.parent >= 0 and td.parent < len(self.il.types):
                pt = self.il.types[td.parent]
                if self.il._type_enum(pt) == 0x12 and 0 <= pt[0] < len(self.meta.typedefs):
                    ptd = self.meta.typedefs[pt[0]]
                    full = (ptd.namespace + '.' if ptd.namespace else '') + ptd.name
                    if full not in ('System.Object', 'System.ValueType') \
                            and ptd.generic_container == -1:
                        base = ' : %s_Fields' % self.type_cname(pt[0])
            align = '__declspec(align(8)) ' if ((td.flags >> 3) & 3) != 0 else ''
            out.append('struct %s%s_Fields%s {' % (align, n, base))
            out.extend(self._instance_fields(td, subst))
            out.append('};')
        named_vt = self._vtable(td, n, out)
        out.append('struct %s_c {' % n)
        out.append('\tIl2CppClass_1 _1;')
        out.append('\tvoid* static_fields;')
        out.append('\tIl2CppRGCTXData* rgctx_data;')
        out.append('\tIl2CppClass_2 _2;')
        if td.vtable_count > 0:
            if named_vt:
                out.append('\t%s_VTable vtable;' % n)
            else:
                out.append('\tVirtualInvokeData vtable[%d];' % td.vtable_count)
        out.append('};')
        out.append('struct %s_o {' % n)
        if not td.is_valuetype:
            out.append('\t%s_c *klass;' % n)
            out.append('\tvoid *monitor;')
        out.append('\t%s_Fields fields;' % n)
        out.append('};')
        return True

    def emit_type(self, td, out):
        if td.name == '<Module>' or td.generic_container != -1:
            return False  # generic definitions have no runtime layout of their own
        self._emit_quartet(td, self.type_cname(td.index), out)
        return True

    def emit_instantiation(self, t, out):
        """Struct quartet for a closed generic instantiation type tuple."""
        if t is None or self.il._type_enum(t) != 0x15:
            return False
        base = self._genericinst_td(t)
        if base is None:
            return False
        td = self.meta.typedefs[base]
        if td.generic_container == -1:
            return False
        n = self.cident(self.il.type_name(t, 0))
        if n in self._inst_emitted:
            return False
        self._inst_emitted.add(n)
        subst = None
        gc = self.meta.generic_containers[td.generic_container] if 0 <= td.generic_container < len(self.meta.generic_containers) else None
        args = self._inst_args(t)
        if gc and args:
            subst = {}
            for k in range(min(gc[1], len(args))):
                subst[gc[3] + k] = args[k]
        self._emit_quartet(td, n, out, subst=subst)
        return True

    def write(self):
        self._inst_emitted = set()
        out = [HEADER_PRELUDE, '']
        count = 0
        for img in self.meta.images:
            for ti in range(img.type_start,
                            min(img.type_start + img.type_count, len(self.meta.typedefs))):
                if self.emit_type(self.meta.typedefs[ti], out):
                    count += 1
        for t in self.il.types:
            if self.emit_instantiation(t, out):
                count += 1
        with open(self.path, 'w', encoding='utf-8') as fh:
            fh.write('\n'.join(out) + '\n')
        return count


# ----------------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------------
