<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>UnsafeSmoke</AssemblyName>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>CS0169;CS0649;CS0108;CS0114;CS8019</NoWarn>
  </PropertyGroup>
</Project>
