"""Compile and run small C# fragments generated by the real recovery pipeline.

Requires iced-x86 and a .NET 8 SDK; never loads or executes the game binary.
This is deliberately NOT a build of final_out or an equivalence test.
"""
import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
from types import SimpleNamespace as NS

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from iced_x86 import Decoder
from il2cpp import Block, Decompiler
from il2cpp import Emitter, Expr, Lifter, MethodDef

INT = (0, 0x08 << 16)
FLOAT = (0, 0x0C << 16)
DOUBLE = (0, 0x0D << 16)
STRING = (0, 0x0E << 16)
ARRAY = (0x5000, 0x1D << 16)
VECTOR = (0, 0x11 << 16)
HIT = (1, 0x11 << 16)


def fixture():
    """Minimum metadata needed for these instruction-level regressions."""
    lift = Lifter.__new__(Lifter)
    methods = [
        MethodDef(0, "get_point", 1, 0, 0, -1, 1, 0, 0, 0, 0),
        MethodDef(1, "get_origin", 2, 0, 0, -1, 2, 0, 0, 0, 0),
    ]
    meta = NS(
        methods=methods,
        typedefs=[NS(name=n, namespace="", is_valuetype=True, generic_container=-1)
                  for n in ("Vector", "Hit", "Ray")],
        method_params=lambda m: [],
    )
    lift.il = NS(
        meta=meta, types=[VECTOR],
        _type_enum=lambda t: (t[1] >> 16) & 0xFF if t else 0,
        type_from_ptr=lambda p: STRING if p == ARRAY[0] else None,
        addr_candidates={0x2000: [("method", 0), ("method", 1)]},
        addr_to_method={0x2000: ("method", 0)},
        returns_sret=lambda t: t == VECTOR,
        value_type_size=lambda td: 12 if td == 0 else None,
        base_chain_tds=lambda td: [td],
        instance_field_chain=lambda td: {},
        # element stride: VECTOR is 12 bytes, references/strings 8
        _sf_field_size=lambda fty, depth: 12 if fty == VECTOR else (8 if fty is not None else None),
    )
    lift.meta, lift.bin = meta, NS()
    lift.regs, lift.out = {}, []
    lift._type_hints, lift._var_types, lift.slot_types = {}, {}, {}
    lift.stack_map, lift.addr_of = {}, {}
    lift.rsp_delta = lift.var_n = 0
    lift._cur_ip = 0
    lift.flags = None
    lift.dry = lift.asm_comments = lift._copying = False
    lift.rt_init_meta = lift.rt_alloc = None
    lift.rt_arrnew, lift.rt_wbarrier = set(), set()
    lift.vt_recv_slot = lift.vt_recv = None
    lift._call_name = lambda va: "sub_2000/*shared body, 2 candidates*/"
    return lift


def execute(lift, encoding, ip=0x1000):
    instructions = list(Decoder(64, bytes.fromhex(encoding), ip=ip))
    for i, ins in enumerate(instructions):
        lift._insn(ins, instructions, i, None, instructions[-1].next_ip)


def generated_loop_fragment():
    """Render a refill-shaped natural loop through the real CFG emitter."""
    def block(bid, *, stmts=(), term=("stop",), cond=None, succs=(), preds=()):
        insn = Decoder(64, b"\x90", ip=0x3000 + bid * 0x10).decode()
        result = Block(bid, [insn])
        result.stmts = list(stmts)
        result.term = term
        result.cond = cond
        result.succs = list(succs)
        result.preds = list(preds)
        return result

    blocks = [
        block(0, stmts=["var t0 = loopSource;"], term=("jcc", 2, 1),
              cond="t0 != 0", succs=(2, 1), preds=(3,)),
        block(1, stmts=["t0 = Refill();"], term=("fall", 2),
              succs=(2,), preds=(0,)),
        block(2, term=("jcc", 4, 3), cond="t0 == 0",
              succs=(4, 3), preds=(0, 1)),
        block(3, stmts=["Tick();"], term=("jmp", 0),
              succs=(0,), preds=(2,)),
        block(4, term=("ret",), preds=(2,)),
    ]
    dec = Decompiler(fixture())
    dec.loop_of_hdr = {0: ({0, 1, 2, 3}, 3)}
    dec.rpo = list(range(len(blocks)))
    dec.pdom = dec._postdominators(blocks, dec.rpo, set(range(len(blocks))))
    dec.phi_copies = {}
    dec._sw_depth = 0
    dec._seh_regions = []
    dec._bstack = []
    dec._pclose = []
    dec._pad_bids = set()
    dec.eh = None
    dec.ip2bid = {b.insns[0].ip: b.bid for b in blocks}
    output = []
    assert dec._emit_loop(blocks, 0, output, set(), 0) == 4
    output = dec._resolve_labels(output)
    text = "\n".join(output)
    assert text.index("while (true)") < text.index("var t0 = loopSource;")
    assert "t0 = Refill();" in text and "goto " not in text
    return text


def generated_fragments():
    roots = []
    for encoding, ty in (("f30f51c1", FLOAT), ("f20f51c1", DOUBLE)):
        lift = fixture()
        lift.regs["XMM1"] = Expr("value", ty, "float")
        execute(lift, encoding)
        roots.append(lift.regs["XMM0"].text)

    lift = fixture()
    first = lift._array_allocation("new string[2]", ARRAY, 0x1000, None)
    lift.regs["RBX"] = first
    for offset, value in (("20", '"left"'), ("28", '"right"')):
        lift.regs["RDX"] = Expr(value, STRING, "str")
        execute(lift, "488953" + offset + "488d4b" + offset)
        address = lift.regs["RCX"]
        dst, src = lift._wb_operands([address.text, value], [address, lift.regs["RDX"]])
        lift._wb_finish(0x1040, dst, src, None)
    second = lift._array_allocation("new string[2]", ARRAY, 0x1080, None)
    array_body = "\n".join(line for _, line, _ in lift.out)

    lift = fixture()
    lift.regs = {"RCX": Expr("&s_40", None, "ptr"),
                 "RDX": Expr("&s_20", None, "ptr")}
    lift.slot_types["s_20"] = HIT
    execute(lift, "e8fb0f0000")  # call 0x2000
    sret_body = "\n".join(line for _, line, _ in lift.out)
    assert lift.regs["RAX"].text == "&s_40"

    return {"sqrt_float": roots[0], "sqrt_double": roots[1],
            "array_body": array_body, "first_array": first.text,
            "second_array": second.text, "sret_body": sret_body,
            "loop_body": generated_loop_fragment()}


def source(f):
    return f"""using System;
struct Vector {{ public float x, y, z; }}
struct Hit {{ public Vector point {{ get; set; }} }}
static class Program
{{
    static int loopSource, loopRefills, loopTicks;
    static float SqrtFloat(float value) => {f['sqrt_float']};
    static double SqrtDouble(double value) => {f['sqrt_double']};
    static int Refill()
    {{
        loopRefills++;
        if (loopRefills == 1) return loopSource = 2;
        return 0;
    }}
    static void Tick()
    {{
        if (++loopTicks > 10) throw new Exception("loop header value was frozen");
        loopSource--;
    }}
    static void HeaderLoop()
    {{
        loopSource = loopRefills = loopTicks = 0;
        {f['loop_body']}
        if (loopRefills != 2 || loopTicks != 2 || loopSource != 0)
            throw new Exception("loop header/refill execution order");
    }}
    static Vector Point(Hit s_20)
    {{
        Vector s_40 = default;
        {f['sret_body']}
        return s_40;
    }}
    static void Arrays()
    {{
        {f['array_body']}
        if (string.Concat({f['first_array']}) != "leftright")
            throw new Exception("array identity / stores");
        if (ReferenceEquals({f['first_array']}, {f['second_array']}))
            throw new Exception("distinct allocations collapsed");
    }}
    static void Main()
    {{
        HeaderLoop();
        Arrays();
        var p = Point(new Hit {{ point = new Vector {{ x = 3, y = 4, z = 5 }} }});
        if (p.x != 3 || p.y != 4 || p.z != 5) throw new Exception("sret receiver");
        foreach (float x in new[] {{ 0f, -0f, 1f, 2f, 4f, 9f, float.Epsilon,
                                    float.MaxValue, float.PositiveInfinity }})
            if (BitConverter.SingleToInt32Bits(SqrtFloat(x)) !=
                BitConverter.SingleToInt32Bits(MathF.Sqrt(x)))
                throw new Exception("float sqrt: " + x);
        if (!float.IsNaN(SqrtFloat(-1)) || !float.IsNaN(SqrtFloat(float.NaN)))
            throw new Exception("float sqrt NaN");
        if (SqrtDouble(9) != 3 || !double.IsNaN(SqrtDouble(-1)) ||
            !double.IsPositiveInfinity(SqrtDouble(double.PositiveInfinity)))
            throw new Exception("double sqrt");
        Console.WriteLine("PASS: loop header, allocation identity, GC-store twins, sret receiver, scalar sqrt");
    }}
}}
"""


def generated_unsafe_project(out):
    """Exercise the actual project writer, not a hand-maintained XML copy."""
    emitter = Emitter.__new__(Emitter)
    emitter.out_dir = str(out)
    emitter.meta = NS(typedefs=[])
    emitter.write_assembly_split(NS(name="UnsafeSmoke.dll", type_start=0, type_count=0))
    project = out / "UnsafeSmoke" / "UnsafeSmoke.csproj"
    (project.parent / "UnsafeSmoke.cs").write_text(
        "public static class UnsafeSmoke {\n"
        "    public static unsafe int Read(int* value) => *value;\n"
        "}\n", encoding="utf-8")
    return project


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="work/csharp-smoke",
                    help="directory for generated C#, compiler output, and report")
    ap.add_argument("--dotnet", default="dotnet",
                    help="path to dotnet with the .NET 8 SDK installed")
    ap.add_argument("--emit-only", action="store_true", help="generate without compiling")
    args = ap.parse_args()
    out = Path(args.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    fragments = generated_fragments()
    (out / "Program.cs").write_text(source(fragments), encoding="utf-8")
    (out / "Smoke.csproj").write_text(
        '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup>'
        '<OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework>'
        '<EnableDefaultCompileItems>false</EnableDefaultCompileItems>'
        '</PropertyGroup><ItemGroup><Compile Include="Program.cs" />'
        '</ItemGroup></Project>\n', encoding="utf-8")
    (out / "NuGet.Config").write_text(
        '<configuration><packageSources><clear /></packageSources></configuration>\n',
        encoding="utf-8")
    unsafe_project = generated_unsafe_project(out)
    report = {"scope": "synthetic instruction-generated C# only; NOT final_out",
              "fragments": fragments, "compiled": False, "executed": False,
              "generated_unsafe_project_compiled": False}
    code = 0
    if not args.emit_only:
        env = dict(os.environ, DOTNET_CLI_TELEMETRY_OPTOUT="1",
                   DOTNET_NOLOGO="1", DOTNET_SKIP_FIRST_TIME_EXPERIENCE="1")
        try:
            run = subprocess.run(
                [args.dotnet, "run", "--project", str(out / "Smoke.csproj"),
                 "--configuration", "Release", "--verbosity", "quiet"],
                capture_output=True, text=True, timeout=180, env=env)
            log = run.stdout + run.stderr
            code = run.returncode
            passed = code == 0 and "PASS:" in run.stdout
            report.update(compiled=passed, executed=passed, exit_code=code)
            build = subprocess.run(
                [args.dotnet, "build", str(unsafe_project),
                 "--configuration", "Release", "--verbosity", "quiet"],
                capture_output=True, text=True, timeout=180, env=env)
            log += build.stdout + build.stderr
            report["generated_unsafe_project_compiled"] = build.returncode == 0
            code = code or build.returncode
            print(log, end="")
        except (OSError, subprocess.TimeoutExpired) as exc:
            code, log = 1, str(exc) + "\n"
            report["error"] = str(exc)
            print(log, end="")
        (out / "run.log").write_text(log, encoding="utf-8")
    (out / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    return code


if __name__ == "__main__":
    raise SystemExit(main())